### ISSUE TITLE
If autoscaling is on, should add lifecycle ignore_changes for read write?

### ISSUE THREAD

**Issue by alantang888** [terraform-aws-modules/terraform-aws-dynamodb-table#14]
Because every time apply, it will set the read and write back to min value.

**Comment by antonbabenko** [comment]
You can set those values to `null`, but Terraform doesn't allow us to use variables inside of ignore_changes.

**Comment by alantang888** [comment]
I tried set value to null. But it will have error `"min_capacity": required field is not set`...

**Comment by max-rocket-internet** [comment]
I can try. Can you post your complete config @alantang888? TBH autoscaling Dynamo with TF has always been quite confusing as some of the settings override each other. Even in the AWS console they have a popup about settings changing once you enable it.

**Comment by alantang888** [comment]
@max-rocket-internet please see below for config. 
I study a while. Look like can't be solved. Because `lifecycle` not work on dynamic block... Also `write_capacity` and `read_capacity` must be set when billing_mode is `PROVISIONED`. 

Thanks for your time.

```
module "dynamodb_table-dummy" {
  source   = "terraform-aws-modules/dynamodb-table/aws"

  name     = "dummy${terraform.workspace == "prod" ? "": format("-%s", terraform.workspace)}"
  hash_key = "id"
  ttl_enabled = true
  ttl_attribute_name = "ttl"

  billing_mode = "PROVISIONED"
  point_in_time_recovery_enabled = terraform.workspace == "prod" ? true: false

  attributes = [
    {
      name = "id"
      type = "S"
    },
    {
      name = "dummy_0"
      type = "S"
    },
    {
      name = "dummy_1"
      type = "S"
    },
    {
      name = "created_at"
      type = "S"
    }
  ]

  global_secondary_indexes = [
    {
      name               = "dummy_1_index"
      hash_key           = "dummy_1"
      range_key          = "created_at"

      projection_type    = "ALL"
      write_capacity     = terraform.workspace == "prod" ? 30: 5
      read_capacity      = terraform.workspace == "prod" ? 5: 5
    },
    {
      name               = "dummy_0_index"
      hash_key           = "dummy_0"
      range_key          = "created_at"

      projection_type    = "ALL"
      write_capacity     = terraform.workspace == "prod" ? 30: 5
      read_capacity      = terraform.workspace == "prod" ? 5: 5
    }
  ]

  read_capacity  = terraform.workspace == "prod" ? 5: 5
  write_capacity = terraform.workspace == "prod" ? 30: 5

  autoscaling_read = {
    target_value       = 70
    max_capacity       = 30000

  }

  autoscaling_write = {
    target_value       = 70
    max_capacity       = 30000
  }

  autoscaling_indexes = {
    dummy_1_index = {
      read_max_capacity  = 30000
      read_min_capacity  = terraform.workspace == "prod" ? 5: 5
      write_max_capacity = 30000
      write_min_capacity = terraform.workspace == "prod" ? 30: 5
    }
    dummy_0_index = {
      read_max_capacity  = 30000
      read_min_capacity  = terraform.workspace == "prod" ? 5: 5
      write_max_capacity = 30000
      write_min_capacity = terraform.workspace == "prod" ? 30: 5
    }
  }
}
```

**Comment by max-rocket-internet** [comment]
I've had a look and I can't really think of a solution for this.

I would say we just add `ignore_changes` lifecycle rule, we do that on autoscaling groups also, but I don't think it's possible for `dynamic` blocks: https://github.com/terraform-providers/terraform-provider-aws/issues/13192

And obviously no interpolation for life cycle rules either: https://github.com/hashicorp/terraform/issues/3116

😞

**Comment by tgam-smickeler** [comment]
Would you be open to creating a 2nd version of this module with a `lifecycle` rule included. I'm would guess there are people who are cloning this repo and basically maintaining their own version and adding in

```
  lifecycle {
    ignore_changes = [
      read_capacity,
      write_capacity
    ]
  }
```

To the end of the module.

**Comment by shmick** [comment]
Would you be open to creating a 2nd version of this module with a `lifecycle` rule included. I'm would guess there are people who are cloning this repo and basically maintaining their own version and adding in

```
  lifecycle {
    ignore_changes = [
      read_capacity,
      write_capacity
    ]
  }
```

To the end of the module.

**Comment by richid** [comment]
I've been fighting to find an elegant solution to this for a couple years. My initial version was to use an external data source and call out to `awscli` to fetch the current table's read and write capacity.

An alternative is to force consumers to set a max/min and create the autoscaling resources regardless. If the max/min are the same value the autoscaling rules would have no effect. This would allow us to set

```terraform
lifecycle {
  ignore_changes = [ read_capacity, write_capacity ]
}
```

in the main config and just delegate to autoscaling.

**Comment by max-rocket-internet** [comment]
Could we have 2 `aws_dynamodb_table` resources in the module, one with the lifecycle rule and one without? and switch between them using count based on some logic?

**Comment by manelpb** [comment]
Any updates on this?

**Comment by antonbabenko** [comment]
@max-rocket-internet Yes, we can have this logic implemented as you described. PR is welcome.

**Comment by max-rocket-internet** [comment]
Awesome. I'll make a PR next week. I also want to open a PR for `terraform-aws-iam`.

**Comment by max-rocket-internet** [comment]
Here's my PR: https://github.com/terraform-aws-modules/terraform-aws-dynamodb-table/pull/43

Could someone verify that this approach works?

**Comment by manelpb** [comment]
@max-rocket-internet I would suggest adding something like "BREAKING CHANGE/IMPORTANT" instead of just a note. Because this will cause a table recreation if not moved

**Comment by max-rocket-internet** [comment]
> I would suggest adding something like "BREAKING CHANGE/IMPORTANT" instead of just a note.

I think "Breaking change" would go in the changelog but I get your point, perhaps it should be more alarming. I'll make some changes.
