### ISSUE TITLE
Cannot lifecycle ignore write_capacity and read_capacity

### ISSUE THREAD

**Issue by bataras** [terraform-aws-modules/terraform-aws-dynamodb-table#17]
Cannot set the lifecycle field for the underlying aws_dynamodb_table. When the table has scaled up, running terraform apply tries to reset the write_capacity to its base value

**Comment by max-rocket-internet** [comment]
Duplicate of https://github.com/terraform-aws-modules/terraform-aws-dynamodb-table/issues/14
