### ISSUE TITLE
KMS CMK key for DynamoDB Global tabel

### ISSUE THREAD

**Issue by ahamansh** [terraform-aws-modules/terraform-aws-dynamodb-table#22]
Hi wanted to know how can we give KMS CMK for DynamoDB global table as KMS is region specific and in global table TF will create table in another region.

**Comment by prukmangathan** [comment]
Any update on this question ? In our organization, we only support CMK and we must use CMK for global tables.

**Comment by bryantbiggs** [comment]
hi all - this is not supported by the AWS provider for Terraform yet so it is not possible. You will need to file a ticket upstream at the Terraform AWS provider to get it added there https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dynamodb_table

**Comment by Proka88MPH** [comment]
AWS Terraform provider added support for this:
https://github.com/hashicorp/terraform-provider-aws/pull/18373
