### ISSUE TITLE
Is it possible to create multiple dynamodb tables in the same directory using this module

### ISSUE THREAD

**Issue by rajpaly** [terraform-aws-modules/terraform-aws-dynamodb-table#23]
If any one already using this module to create multiple tables from same directory please share the code.  i wanted to use workspace but looks like it has limitation on creating workspace manually.

**Comment by rajpaly** [comment]
@alantang888  I see you are using the workspace idid you had to create them manually first?

**Comment by alantang888** [comment]
Yes, I create those workspace manually.

**Comment by karthik8899** [comment]
@rajpaly - Were you able to resolve this for mulitple tables. Any git hub reference for your example?

**Comment by bryantbiggs** [comment]
yes, I don't see why you wouldn't be able to. you can use the variable `create_table` to determine if a table should or should not be created for specific workspaces
