### ISSUE TITLE
DynamoDB Output ID

### ISSUE THREAD

**Issue by andrew-secret** [terraform-aws-modules/terraform-aws-dynamodb-table#25]
Hey @antonbabenko @max-rocket-internet,

I currently building a side project with your wonderful `serverless.tf` modules ✨  I love it so far 🥰

One thing I couldn't figure out yet was this line here:
https://github.com/terraform-aws-modules/terraform-aws-dynamodb-table/blob/b2a13ad6facf06e9c78de4138bcd2b9c1511e1c2/outputs.tf#L6

My goal is to use the `ID` of the DynamoDB table in my `AppSync` module. Apparently when I consume it in `AppSync` module it add the the twice:

```hcl
arn:aws:dynamodb:eu-central-X:XXXXXXXXXX:table/arn:aws:dynamodb:eu-central-X:XXXXXXXXXX::table/my-table
```

I want to use the output of the ID in my `AppSync` module. So what I did is:

1. define a variable:
```hcl
variable this_dynamodb_table_id {
  type = string
}
```

2. Jump into the datasource configuration in my `AppSync` module and add the variable:

```hcl
    dynamodb1 = {
      type = "AMAZON_DYNAMODB"

      # Note: dynamic references (module.dynamodb_table1.this_dynamodb_table_id) do not work unless you create this resource in advance
      table_name = var.this_dynamodb_table_id
      region     = var.region
    }
```

3. Last step I go to my `main.tf` in the root and add the modules:

```
module my_test_api {
  source = "./modules/my-test-api"
  region = var.region
  this_dynamodb_table_id = module.my_table.this_dynamodb_table_arn
}
```

After excute `terraform plan` if receive this output:

```hcl
arn:aws:dynamodb:eu-central-X:XXXXXXXXXX:table/arn:aws:dynamodb:eu-central-X:XXXXXXXXXX::table/my-table
```

When I just add a string value w/o using a variable it works as expected.

Maybe someone can tell me what I'm doing wrong here or is it a bug, because of the concat function? 

Cheers
André

**Comment by antonbabenko** [comment]
Hi @andrew-secret ,

There is an error in your `appsync` module argument. `table_name` should be just the name of the table, not `arn`.

Try it like this:
```
module my_test_api {
  source = "./modules/my-test-api"
  region = var.region
  this_dynamodb_table_id = module.my_table.this_dynamodb_table_id
}
```

Also, there is [this example in serverless.tf-playground repository](https://github.com/antonbabenko/serverless.tf-playground/blob/master/terraform/appsync.tf#L25).

**Comment by andrew-secret** [comment]
Thank you In knew it was a layer 8 problem 😅

**Comment by antonbabenko** [comment]
No problems, we all have PEBCAK from time to time 👍
