### ISSUE TITLE
Add possibility to retain table when destroying the resource  

### ISSUE THREAD

**Issue by rjcoelho** [terraform-aws-modules/terraform-aws-dynamodb-table#33]
Because if for some reason/mistake, I destroy the resource, I want to retain the table (its the user data)
Just expose the lifecycle meta-arg, or the prevent_destroy flag
Keep it to false by default
Thanks

**Comment by antonbabenko** [comment]
Terraform does not allow to use of variables inside of lifecycles meta-arguments, so we can't do much about it.

This is one of the most popular requests also in the EC2 instance module we have.

In the future, Terraform will support a special meta argument to indicate that resources should be retained even after deletion to prevent things you have described.

**Comment by rjcoelho** [comment]
lifecycle {
    prevent_destroy = true
}

Can I pass this to the module ?
