### ISSUE TITLE
Optionally add cloudwatch consume alarms when autoscaling is enabled

### ISSUE THREAD

**Issue by rjcoelho** [terraform-aws-modules/terraform-aws-dynamodb-table#36]
One for read, one for write and one each GSI (read and write).
I can do this on my modules, but I feel this pattern of autoscaling + alarms is a usual pattern.
If you agree I can open a PR.

Thanks,
Rui

**Comment by antonbabenko** [comment]
Please add this but make it disabled by default for backward compatibility and add granular boolean flags to turn on/off these resources.

**Comment by rjcoelho** [comment]
https://github.com/terraform-aws-modules/terraform-aws-dynamodb-table/pull/37
