### ISSUE TITLE
stream arn reference

### ISSUE THREAD

**Issue by nivincp** [terraform-aws-modules/terraform-aws-dynamodb-table#45]
stream arn in output seems incorrect

https://github.com/terraform-aws-modules/terraform-aws-dynamodb-table/blob/4e2c8ec638d03276038766afa24cdca41453ef67/outputs.tf#L13

shouldn't this be ```tfvar.stream_enabled ? try(aws_dynamodb_table.this[0].stream_arn, aws_dynamodb_table.autoscaled[0].stream_arn, "") : null```

**Comment by antonbabenko** [comment]
Thank you for reporting this issue! Fixed in #46

**Comment by antonbabenko** [comment]
This issue has been resolved in version 1.2.1 :tada:
