### ISSUE TITLE
Support for continuous backups without point-in-time-recovery

### ISSUE THREAD

**Issue by dhmistry3** [terraform-aws-modules/terraform-aws-dynamodb-table#50]
Continuous backups enabled with point-in-time-recovery disabled doesn't appear possible with this module.

**Comment by antonbabenko** [comment]
Have you tried setting [`point_in_time_recovery_enabled = true`](https://github.com/terraform-aws-modules/terraform-aws-dynamodb-table#input_point_in_time_recovery_enabled)?

It is used here - https://github.com/terraform-aws-modules/terraform-aws-dynamodb-table/blob/master/main.tf#L18-L20

**Comment by dhmistry3** [comment]
I want point-in-time-recovery disabled with continuous backup enabled.  So ending with this output:
"ContinuousBackupsDescription": {
                    "continuousBackupsStatus": "ENABLED",
                    "pointInTimeRecoveryDescription": {
                        "pointInTimeRecoveryStatus": "DISABLED"
                    }
                },

**Comment by antonbabenko** [comment]
Is it supported by the AWS provider?

If not, we can't do much.

If yes, please open a PR.

PS: There is/was [issue template](https://github.com/terraform-aws-modules/terraform-aws-dynamodb-table/issues/new?assignees=&labels=&template=feature_request.md) when you open an issue.
