### ISSUE TITLE
Table class is not supported in this module, which causes an issue for the tables already created with the table class set. 

### ISSUE THREAD

**Issue by haytham-salhi** [terraform-aws-modules/terraform-aws-dynamodb-table#52]
## Description

Table class is not supported in this module, which causes an issue for the tables already created with the table class set. Please see https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dynamodb_table#table_class.

## Versions

- Module version [Required]: Latest

- Terraform version:
Latest
- Provider version(s):
AWS (Latest)

## Reproduction Code [Required]

No way to provide the table class in this module!

N/A

## Expected behavior

Table class attribute should be supported.

## Actual behavior

Table class is not set, making it null (which is considered not correct value by AWS).

![image](https://user-images.githubusercontent.com/11832107/170966753-94641fae-2247-43f5-a4a7-e3611a39fa1a.png)

### Terminal Output Screenshot(s)

N/A

## Additional context

N/A

**Comment by haytham-salhi** [comment]
Hi @antonbabenko, can you plz check the above issue?

**Comment by antonbabenko** [comment]
PR is welcome.

**Comment by haytham-salhi** [comment]
@antonbabenko thanks. Plz review: https://github.com/terraform-aws-modules/terraform-aws-dynamodb-table/pull/53

**Comment by haytham-salhi** [comment]
@antonbabenko can we get this PR merged plz?

**Comment by antonbabenko** [comment]
This issue has been resolved in version 1.3.0 :tada:
