### ISSUE TITLE
propagate_tags variable is not supported in the module which is preventing the replication of tags to DynamoDB replicas table in other region.

### ISSUE THREAD

**Issue by huzaifa-binafzal** [terraform-aws-modules/terraform-aws-dynamodb-table#58]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - Yes ✅:  terraform-provider-aws v4.23.0 has fixed the issue by adding propagate_tags variable. Details can be found on the link. https://github.com/hashicorp/terraform-provider-aws/blob/v4.23.0/CHANGELOG.md

## Is your request related to a problem? Please describe.
 Currently we're facing the issue where there is no way to propagate tags to the DynamoDB replicas table in other region.

## Describe the solution you'd like.
 This issue has been fixed in the new release v4.23.0 of terraform-provider-aws. details can be found on the link. https://github.com/hashicorp/terraform-provider-aws/blob/v4.23.0/CHANGELOG.md , resource/aws_dynamodb_table: Add replica.*.propagate_tags argument to allow propagating tags to replicas (https://github.com/hashicorp/terraform-provider-aws/issues/25866).  We need to update the module by adding propagate_tags variable inside replica_regions variable that we already have.

**Comment by huzaifa-binafzal** [comment]
@antonbabenko Please review the PR: https://github.com/terraform-aws-modules/terraform-aws-dynamodb-table/pull/59 for this issue.

**Comment by antonbabenko** [comment]
Fixed in #59
