### ISSUE TITLE
Introduce the option to specify lifecycle rules on the dynamoDb tables

### ISSUE THREAD

**Issue by pmason56** [terraform-aws-modules/terraform-aws-dynamodb-table#60]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - Yes ✅
  
## Is your request related to a problem? Please describe.
The module does not currently have the option to specify the prevent destroy lifecycle rules on the DynamoDb table

## Describe the solution you'd like.
I would like to be able to introduce a variable similar to 
`variable "prevent_destruction_of_table" {
  description = "Enable to prevent destruction of the DynamoDb table. No other resources are protected by this flag."
  default  = false
}`

This could then be used to toggle lifecycle rules on the DynamoDB table in main
`  lifecycle {
    prevent_destroy = var.prevent_destruction_of_table
  }
`

## Describe alternatives you've considered.
Currently unable to specify lifecycle rules on modules as per this feature request https://github.com/hashicorp/terraform/issues/18367

**Comment by antonbabenko** [comment]
Unfortunately, it is still not possible to do in Terraform - https://github.com/hashicorp/terraform/issues/3116
