### ISSUE TITLE
Add the possibility to configure Terraform Resource Lifecycle

### ISSUE THREAD

**Issue by benkeil** [terraform-aws-modules/terraform-aws-dynamodb-table#63]
## Is your request related to a problem? Please describe.

It is not possible to set terraform resource lifecycles.

## Describe the solution you'd like.

Add a new property to set it.

## Additional context

We need to add `prevent_destroy` to the table.

**Comment by antonbabenko** [comment]
Not everyone needs it, but Terraform does not allow us to set it using variables, so we can't make it in the module.

**Comment by benkeil** [comment]
is there already a feature request to support that in terraform?

**Comment by antonbabenko** [comment]
Yes, there are two related issues:
https://github.com/hashicorp/terraform/issues/3116
https://github.com/hashicorp/terraform/issues/27360
