### ISSUE TITLE
Support removing a table without deleting it

### ISSUE THREAD

**Issue by quad** [terraform-aws-modules/terraform-aws-dynamodb-table#78]
## Is your request related to a problem? Please describe.

**Right now**: if we remove a table's configuration, it destroys the table

**Expected behaviour**: a way to remove a table's configuration without deleting the table.

## Describe the solution you'd like.

We could add a `prevent_destroy = true` boolean variable (default value: `false` to retain existing behaviour) that would control the `lifecycle { prevent_destroy = true }` to the `aws_dynamodb_table` resource.

## Describe alternatives you've considered.

Right now, the best solution is manually removing the table from the Terraform state. Super inconvenient and doesn't mesh well with CI/CD practices.

**Comment by bryantbiggs** [comment]
This is outside of our control - this is how Terraform is designed to function

**Comment by quad** [comment]
Doesn't Terraform offers the `lifecycle { prevent_destroy = true }` option specifically for this kind of situation?

**Comment by bryantbiggs** [comment]
No 
> This meta-argument, when set to true, will cause Terraform to reject with an error any plan that would destroy the infrastructure object associated with the resource, as long as the argument remains present in the configuration.

It just simply throws an error that you are trying to do an operation that has been marked as not permitted

**Comment by quad** [comment]
😭 cheers
