### ISSUE TITLE
Failure when trying to import existing AutoScaling policy

### ISSUE THREAD

**Issue by sebastianarca** [terraform-aws-modules/terraform-aws-dynamodb-table#79]
## Description

Using this module I want to import existing resources created by the web console.

Everything goes fine, until I try to import the resource related to `aws_appautoscaling_policy.table_read_policy[0]` and `aws_appautoscaling_policy.table_write_policy[0]`, where the error says that the desired resource is not found::
`Error: Cannot import non-existent remote object`

After multiple searches on the internet and going through the documentation I tried to import the existing resources, according to how the module is assembled it should be: `dynamodb/table/example/dynamodb:table:ReadCapacityUnits/DynamoDBReadCapacityUtilization:table/example`

This identifier belongs to the structure:
service-namespace = dynamodb
resource-id = table/example
scalable-dimension = dynamodb:table:ReadCapacityUnits
policy-name = DynamoDBReadCapacityUtilization:table/example

However, when executing the command:  `aws application-autoscaling describe-scaling-policies  --service-namespace dynamodb`

I obtain the following structure
```
             "PolicyARN": "arn:aws:autoscaling:us-west-2:00000000:scalingPolicy:xxxxxxxxxx-98xx:resource/dynamodb/table/example:policyName/$example",
            "PolicyName": "$example-scaling-policy",
            "ServiceNamespace": "dynamodb",
            "ResourceId": "table/example",
            "ScalableDimension": "dynamodb:table:ReadCapacityUnits", 
            "PolicyType": "TargetTrackingScaling",
            "TargetTrackingScalingPolicyConfiguration": {
                "TargetValue": 70.0,
                "PredefinedMetricSpecification": {
                    "PredefinedMetricType": "DynamoDBReadCapacityUtilization"
                }
            },

```

Using this value I construct the following identifier which does work:
`dynamodb/table/example/dynamodb:table:WriteCapacityUnits/$example-scaling-policy`

The problem is that Terraform is now trying to destroy the resource:
```
  module.dynamodb.aws_appautoscaling_policy.table_read_policy[0] must be replaced
-/+ resource "aws_appautoscaling_policy" "table_read_policy" {
      ~ alarm_arns         = [                                                                                                           
          - "arn:aws:cloudwatch:us-west-2:000000000000:alarm:TargetTracking-table/example-AlarmHigh-xxxxxxxxxx",
          - "arn:aws:cloudwatch:us-west-2:000000000000:alarm:TargetTracking-table/example-AlarmLow-xxxxxxxxxx",
          - "arn:aws:cloudwatch:us-west-2:000000000000:alarm:TargetTracking-table/example-ProvisionedCapacityHigh-xxxxxxxxxx",
          - "arn:aws:cloudwatch:us-west-2:000000000000:alarm:TargetTracking-table/example-ProvisionedCapacityLow-xxxxxxxxxx",
        ] -> (known after apply)                         
      ~ arn                = "arn:aws:autoscaling:us-west-2:000000000000:scalingPolicy:xxxxxxxxxx:resource/dynamodb/table/example:policyName/$example-scaling-policy" -> (known after apply)
      ~ id                 = "$example-scaling-policy" -> (known after apply)
      ~ name               = "$example-scaling-policy" -> "DynamoDBReadCapacityUtilization:table/example" # forces replacement     
    }
```

- [ X] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]: 4.0.0

- Terraform version: v1.6.3

- Provider version(s): v5.25.0

**Comment by vishal-elimu** [comment]
@sebastianarca The issue is with **PolicyName**, use the same policy name as returned by `aws application-autoscaling describe-scaling-policies  --service-namespace dynamodb` command and add `\` at the start of policy name (i.e after scalable-dimension, add `\$$example-scaling-policy` as the policy name).  

I confirmed with aws dynamodb team, they stated that it is the **default way of creating name of policy**  (i.e having $ in policy name)

Try below and that should work for you

`terraform import module.dynamodb.aws_appautoscaling_policy.table_read_policy[0] dynamodb/table/example/dynamodb:table:ReadCapacityUnits/\$$example-scaling-policy`
