### ISSUE TITLE
Workaround for new GSI creation for existing large DynamoDB tables which take a very long time

### ISSUE THREAD

**Issue by allanliu** [terraform-aws-modules/terraform-aws-dynamodb-table#86]
## Is your request related to a new offering from AWS?
No
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - No 🛑: please wait to file a request until the functionality is avaialble in the AWS provider
  - Yes ✅: please list the AWS provider version which introduced this functionality

## Is your request related to a problem? Please describe.

When trying to add GSI to existing DynamoDB with large amounts of data, the create (e.g.`UpdateTable`) process can take up to many days. Currently the only allowed Terraform behavior using [aws_dynamodb_table](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dynamodb_table#global_secondary_index) behavior for applying changes with these GSI creations is to synchronous in that Terraform waits until the GSI is in `ACTIVE` state before moving on ([example from src](https://github.com/hashicorp/terraform-provider-aws/blob/ac25cb8af271228fef76ccc80b835b4306a7db58/internal/service/dynamodb/table.go#L1021)). Terraform applies running for that long creates a few problems for us:
1. Deploying changes to the service managing terraform applies either is blocked or the terraform.
2. Exceeding build time limits when integrating Terraform into our CI/CD process.
3. It looks like there's a global max value for the `timeout` parameter of 24h, which is not sufficient for many of the DynamoDB tables that we manage.

## Describe the solution you'd like.

An optional parameter for [global_secondary_resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dynamodb_table#global_secondary_index) that allows the `UpdateTable` to be considered successful as long as the GSI goes into `CREATING` state would serve as a workable solution for us (i.e. essentially an async flag, etc.).

However, we're open to other ideas as well for getting around these blocking long wait times on GSI creation.

## Describe alternatives you've considered.

1. Our current solution is just letting the apply error out due to the Terraform timeout. Letting the apply stay in `ERROR` state until the GSI backfill is completed on the AWS backend, before reapplying. This presents multiple problems in that: 1) the resource is in `ERROR` state for potentially days 2). Any operations in Terraform that takes place after the GSI creation can not run until the GSI is in `ACTIVE` state 3) This does not integrate well into CI/CD pipelines.
2. An alternative that we're discussing is moving GSI creation out of Terraform completely, and manage it with custom code. However that presents many complexities that we have deal with, many of which will be related to managing sources partially in Terraform still. This solution appears to be a dilemma in that it'll be messy regardless (and much cleaner if there were a native Terraform one).

## Additional context

Thanks!

**Comment by bryantbiggs** [comment]
This is an API or provider level issue, nothing related to the module
